routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Product;
use App\Models\Category;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\ProductsController;
use App\Http\Controllers\ProductsController as PC;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderItemController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can ash web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/admin/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


Route::get('/', function () {
    $products = Product::latest()->get();/*eta Product::latest()->with('category')->get() ; with use bhako cha because hamle Product bhnee model ma define gareko bhayera tara if with use garna pardaina bhne without use garna sakinxa like this: Product::latest()->without('category')->get(); */ 
    return view('home',['products'=>$products] );
});

Route::get('/dashboard',[ProductsController::class,'index'])->name('home');
// Route::get('/products/search', [ProductsController::class, 'search'])->name('products.search'); //first ma ProductsController ma search function banaune then web.php ma route banaune//
Route::resource('/products',PC::class)->only(['index','show']); //esari resurces ko index ra show matra dekhau bhnna milxa //
Route::get('search',[SearchController::class, 'search'])->name('search');

Route::get('/categories/{category}',function(Category $category){
    // $products = Product::whereCategoryId($category->id)->get();
    $products = $category->products;
    return view('category',['products' => $products, 'category' => $category]);
});/*yo garda tyo category ma bhako sabai products haru dekhauxa */
/*yo garda products haru ko category call hunxa*/

Route::resource('order',OrderController::class);
Route::post('cart',[OrderItemController::class, 'store'])->name('add_to_cart')->middleware('auth'); //cart ma add garna agadi logged in hunuparxa //

//admin routing
/*yo group bhitra ko sabai component lai authentication chaixa bhneko */
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [DashboardController::class,'index'])->name('dashboard');  /*dashboard ma pugna pani authorization chiaxa */
    // Route::get('/admin/products', [ProductsController::class,'index'])->name('products_list');/*product_list bhnne name diyo bhne routing sajilo hunxa */
    // Route::get('/admin/products/create', [ProductsController::class,'create'])->name('create_product');
    // Route::post('/admin/products/store', [ProductsController::class, 'store']);
    // Route::get('/admin/products/edit/{product}', [ProductsController::class, 'edit']);
     Route::resource('products',ProductsController::class);
     Route::resource('categories',CategoriesController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = [
        'product_name',
        'product_desc',
        'image',
        'price',
        'category_id'
    ];

    protected $attributes = [
        'image' => '',
    ];
    protected $with =['category'];

    public function category()/*here laravel will undersatnd category means category_id*/
    {
        //hasOne , hasMany, belongsTo
       return $this ->belongsTo(Category::class);/*mathi category rakheko bhayera laravel le bujhxa category_id bhnera so ,category_id lekhirkhnu pardiana*/
    }
    public function scopeSearch($query, array $terms)  //hamle eta second argument pathayo array type ko terms bhnera //search controller ma array banaye paxi eta fuunction banako //query bydefault laravel nai pass gardinxa//
    {
        $search = $terms['search'];
        $category = $terms['category'];
        $query->when($search, function($query) use($search){
            return $query->where('product_name','like', '%'. $search .'%')
            ->orWhere('product_desc', 'like', '%'.$search .'%');
        }
        );
    $query->when($category, function($query, $category){
        return $query->whereCategoryId($category);
    });
       // This is another way instead of using when by using if//
        // if ( $terms['search'] !== '' ) //yedi search null haina bhne tala ko function run garauxa//
        // {
        //     $query->where('product_name', 'like', '%'. $terms['search'] .'%') //product name ko adhar ma search garxa//
        //     ->orWhere('product_desc', 'like', '%'. $terms['search'] .'%'); //product desc ko adhar ma search garxa // 
        // }
         return $query;
}
}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use Intervention\Image\Facades\Image;


class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->get();
        return view('admin.products.index',['products' => $products] );
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.products.create', ['categories'=> $categories] );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request; /*data haru json format ma dekhauxa */
        $validated = $request->validate([
            'product_name' => 'required|max:100|unique:products',
            'product_desc' => 'required',
            'price' => 'required',
            'category_id' => 'required|integer|min:1',
        ],
        
            [
                'required' => 'This field is very much required to be fillled', /* required ko case ma yo msg dekhaune */
                'max' => 'this is too long',
                'product_desc.required' => 'Product desc should not be less than 100 words' , /*yo chai specific element ko name diyera */
                'category_id.required' => 'minimum one item need to be selected',
            ],
        
    );
   
        $product = new Product;
        $product->product_name = $request->input('product_name');
        $product->product_desc = $request->input('product_desc');
        $product->price = $request->input('price');
        $product->category_id = $request->input('category_id');
        if ($request->hasFile('image_upload')) {
            //uploading image to images folder
            $name = $request->file('image_upload')->getClientOriginalName();
            $request->file('image_upload')->storeAs('public/images',$name); 
            //croping the image and saving it to thumbnail folder inside images //
            // $image_resize =Image::make(storage_path('app/public/images/'.$name));
            // $image_resize->resize(550, 750);
            // $image_resize->save(storage_path('app/public/images/thumbnail/' .$name)); //images bata resize garisakera thumbnail ma rakhnne */
            $product->image = $name ; /*database ma save gareko name matra pass garera without passing whole path */
            // image_crop($name, 550, 750);
        }  
      
        if($product->save()){
            // return redirect()->route('/admin/products');/*save successful bhayo bhne route ma jane */
            return redirect()->route('admin.categories.index'); /*agadi route ma hamle rakheko name */
        }else {
            return redirect()->back(); /*save unsuccessful bhayo bhne return back */
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('admin.products.edit', ['product'=> $product,'categories'=> $categories] );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Product $product) /*yo bhneko route ra model binf gareko */
    {
        //  $this->authorize('update', $product);
    //    return $request;
    // $products = Product::find($product->id);

    $validated = $request->validate([
        'product_name' => 'required|max:100|unique:products',
        'product_desc' => 'required',
        'price' => 'required|integer',
        'category_id' => 'required|integer|min:1',
    ],
        [
            'required' => 'this field shouldnot be empty',
            'max' => 'shouldnot be longer than 10 characters',
            'integer'=>'only numerical value',

        ], );


        $product = new Product;
        $product->product_name = $request->input('product_name');
        $product->product_desc = $request->input('product_desc');
        $product->price = $request->input('price');
        $product->category_id = $request->input('category_id');
        if ($request->hasFile('image_upload')) {
            // uploading image to images folder
            $name = $request->file('image_upload')->getClientOriginalName();
            $request->file('image_upload')->storeAs('public/images', $name);
            // croping the image and saving it to thumbnail folder inside images folder
            // $image_resize = Image::make(storage_path('app/public/images/'.$name));
            // $image_resize->resize(550, 750);
            // $image_resize->save(storage_path('app/public/images/thumbnail/'.$name));
            image_crop($name, 550, 750);
            $product->image = $name;
        }
        // return $product;
        if($product->save()){
            return redirect()->route('admin.products.index');
        }else {
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
     public function destroy(Product $product)
    {
        $product->delete();
        return back();
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;

class ProductsController extends Controller

{
    public function index(){    //yo function ho//
        $products = Product::latest()->get();
        return view('home', ['products' => $products] );
    }
    
    public function show(Product $product){
        return view('product', compact('product') );
    }
    
    public function search(){
        return 'this is search';
    }

    // public function index(){
    //     $products = Product::latest()->get();
    //     // $singleProduct = products::latest()->take(1)->get();
    //     $threeProduct = Product::latest()->skip(1)->take(3)->get();
    //     $twoProduct = Product::latest()->skip(4)->take(2)->get();
	//     return view('home',['products'=>$products,'threeProduct'=>$threeProduct,'twoProduct'=>$twoProduct]);
    // }
    // public function show(Product $product){
    //     return view('product',compact('product') );
    // }
    // public function search(){
        
    // }
    
    
}

resources/views/admin/products/create.blade.php
<x-admin.layout>
    <div class="az-content az-content-dashboard">
        <div class="container">
          <div class="az-content-body">
            <h2>Create Product</h2>
            <form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                {{-- <x-forms.input type="text" name='full_name'/>    esma j j atrributr rakhyo,tyo input.blade ma change garna milxa  --}}
                Product Name : <input type="text" name="product_name" id="" class="form-control" value="{{ old('product_name') }}" 
                @error('product_name')
                    style="border-color: red;"
                @enderror ><br>
                @error('product_name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
               
                Product Description: <textarea name="product_desc" id="" cols="30" rows="10" class="form-control">{{ old('product_desc') }}</textarea><br>
                @error('product_desc')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror

                Price: <input type="text" name="price" id="" class="form-control" value=" {{ old('price') }}"><br>
                @error('price')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror

                Category: 
                <x-forms.select name="category_id" class="form-control">
                <option value='0'>Select</option>
                @foreach ($categories as $category)
                    <option value= "{{ $category->id }}" @if ($category->id == old('category_id')) selected @endif>{{$category->name}}</option>
                @endforeach   
                
                @error('category_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror   

                <input type="file" name="image_upload" id="">
            </x-forms.select> <br>
                 <input type="submit" name="Submit" value="save" class="form-control">
            </form>
          </div>
        </div>
    </div>
</x-admin.layout>

resources/views/admin/products/edit.blade.php
<x-admin.layout>
    <div class="az-content az-content-dashboard">
        <div class="container">
          <div class="az-content-body">
              <h2>Update Product: {{ $product->product_name}}</h2>
              <form action="{{route('admin.products.update', $product->id)}}" method="POST">
                @method('PUT') {{--ROUTE le update ko lagi PUT/PATCH dekha cha when u see in rote list but form ma POST matra rakhna milxa so  here @method garera PUT rakhne--}}
                @csrf
                {{-- <x-forms.input type="text" name='full_name'/>    esma j j atrributr rakhyo,tyo input.blade ma change garna milxa  --}}
                Product Name : <input type="text" name="product_name" id="" class="form-control" value="{{ $product->product_name}}"><br>
                {{-- @error('product_name')  <div class="alert alert-danger">{{ $message }}</div>  @enderror --}}

                Product Description: <textarea name="product_desc" id="" cols="30" rows="10" class="form-control">{{ $product->product_desc}}</textarea><br>
                {{-- @error('product_desc')  <div class="alert alert-danger">{{ $message }}</div>  @enderror --}}

                Price: <input type="text" name="price" id="" class="form-control" value="{{ $product->price}}"><br>
                {{-- @error('price')  <div class="alert alert-danger">{{ $message }}</div>  @enderror --}}
                Category: 
                <x-forms.select name="category_id" class="form-control">
                    <option value='0'>Select</option>
                    @foreach ($categories as $category)
                        <option value= "{{ $category->id }}" @if ($category->id == $product->category_id) selected @endif>{{$category->name}}</option>
                        {{-- <option value= "{{ $category->id }}" {{$category->id == $product->category_id ? "selected" : '' }}>{{$category->name}}</option> mathi ko ra yo same ho --}}
                    @endforeach
                </x-forms.select><br>

                {{-- <select name="category_id" id=""><option value='0'>Select</option>
                    @foreach ($categories as $category)
                    <option value= "{{ $category->id }}">{{$category->name}}</option>
                    @endforeach
                    </select><br> --}}
                    <input type="submit" name="Submit" value="Save" class="form-control">
            </form>
           
          </div>
        </div>
    </div>
</x-admin.layout>

resources/views/admin/products/index.blade.php
<x-admin.layout>
<div class="az-content az-content-dashboard">
    <div class="container">
        <div class="az-content-body">
{{--     
<a href="/admin/products/create">Create Product</a> --}}
<a href="{{ route('admin.products.create') }}">Create Product</a> {{-- yo garda path change garepani dherai problem creatae gardaina --}}
<table width='900' align='center'>
    <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Description</td>
        <td>Price</td>
        <td>Action</td>
    </tr>
    @foreach ($products as $product)
    <tr>
        <td>{{ $product->id}}</td>
        <td>{{ $product->product_name}}</td>
        <td>{{substr($product->product_desc,0,50)}}</td>
        <td>{{$product->price}}</td>
        <td>
            <a href="{{route('admin.products.edit' ,$product->id )}}">Edit</a>
                <form method="POST" action="{{route('admin.products.destroy',$product->id)}}">
                    @method('DELETE')
                    @csrf
                    <a href="#" onclick="event.preventDefault();
                    this.closest('form').submit();"> Delete</a>
                    </form>
        </td>
    </tr>
        @endforeach
</table>
</div>
</div>
</div>
</x-admin.layout>