routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Product;
use App\Models\Category;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\ProductsController;
use App\Http\Controllers\ProductsController as PC;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderItemController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can ash web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/admin/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


Route::get('/', function () {
    $products = Product::latest()->get();/*eta Product::latest()->with('category')->get() ; with use bhako cha because hamle Product bhnee model ma define gareko bhayera tara if with use garna pardaina bhne without use garna sakinxa like this: Product::latest()->without('category')->get(); */ 
    return view('home',['products'=>$products] );
});

Route::get('/dashboard',[ProductsController::class,'index'])->name('home');
// Route::get('/products/search', [ProductsController::class, 'search'])->name('products.search'); //first ma ProductsController ma search function banaune then web.php ma route banaune//
Route::resource('/products',PC::class)->only(['index','show']); //esari resurces ko index ra show matra dekhau bhnna milxa //
Route::get('search',[SearchController::class, 'search'])->name('search');

Route::get('/categories/{category}',function(Category $category){
    // $products = Product::whereCategoryId($category->id)->get();
    $products = $category->products;
    return view('category',['products' => $products, 'category' => $category]);
});/*yo garda tyo category ma bhako sabai products haru dekhauxa */
/*yo garda products haru ko category call hunxa*/

Route::resource('order',OrderController::class);
Route::post('cart',[OrderItemController::class, 'store'])->name('add_to_cart')->middleware('auth'); //cart ma add garna agadi logged in hunuparxa //

//admin routing
/*yo group bhitra ko sabai component lai authentication chaixa bhneko */
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [DashboardController::class,'index'])->name('dashboard');  /*dashboard ma pugna pani authorization chiaxa */
    // Route::get('/admin/products', [ProductsController::class,'index'])->name('products_list');/*product_list bhnne name diyo bhne routing sajilo hunxa */
    // Route::get('/admin/products/create', [ProductsController::class,'create'])->name('create_product');
    // Route::post('/admin/products/store', [ProductsController::class, 'store']);
    // Route::get('/admin/products/edit/{product}', [ProductsController::class, 'edit']);
     Route::resource('products',ProductsController::class);
     Route::resource('categories',CategoriesController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    public function products(){
        return $this->hasMany(Product::class);
    }

    // public function scopeSearch($query, array $terms)
    // {
       
    //     if ( $terms('search') !== '' ) {
    //         $query->where('product_name', 'like', '%'. request('search') .'%') //product name ko adhar ma search garxa//
    //         ->orWhere('product_desc', 'like', '%'. request('search') .'%'); //product desc ko adhar ma search garxa // 
    //      }
    //      return $query;
    // }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.categories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'slug' =>'required|unique:categories'
        ]);
        // $slug = strtolower( str_replace(' ','-',$request->input('name')) );  // slug banauna lowercase gareko ani space ma - haleko ani slug unique hunuparxa
        // $categories = Category::whereSlug($slug)->get();
        // // dd($categories);
        // if( $categories-> count() > 0){
        //     return redirect()->back()->withErrors(['slug must be unique']);
        // }

        $category = new Category();
        $category->name = $request->input('name');
        $category->desc = $request->input('description');
        $category->parent_id = $request->input('parent_id');
        $category->slug = $slug = $request->input('slug');
        $category->save();
        return redirect()->route('admin.categories.index');

        // $category = Category::create([
        //     'name' => $request->input('name'),
        //     'description' => $reuest->input('description'),
        //     'parent_id' => $request->input('parent_id')
        // ])
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::all();
        return view('admin.categories.edit', [
            'category'=> $category,
            'categories' => $categories
        ] );   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name'=>'required',
            'slug' =>'required|unique:categories'
        ]);
        // $slug = strtolower( str_replace(' ','-',$request->input('name')) );  // slug banauna lowercase gareko ani space ma - haleko ani slug unique hunuparxa
        // $categories = Category::whereSlug($slug)->get();
        // // dd($categories);
        // if( $categories-> count() > 0){
        //     return redirect()->back()->withErrors(['slug must be unique']);
        // }

        $category->name = $request->input('name');
        $category->desc = $request->input('description');
        $category->parent_id = $request->input('parent_id');
        $category->slug = $slug = $request->input('slug');
        $category->save();
        return redirect()->route('admin.categories.index');

        // $category = Category::create([
        //     'name' => $request->input('name'),
        //     'description' => $reuest->input('description'),
        //     'parent_id' => $request->input('parent_id')
        // ])
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return back();
    }
}

resources/views/admin/categories/create.blade.php
<x-admin.layout>
    <div class="az-content az-content-dashboard">
        <div class="container">
          <div class="az-content-body">
            <h2>Create Category</h2>
            <form action="{{ route('admin.categories.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                {{-- <x-forms.input type="text" name='full_name'/>    esma j j atrributr rakhyo,tyo input.blade ma change garna milxa  --}}
                Category Name : <input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}" 
                @error('name')
                    style="border-color: red;"
                @enderror
                >
                Category Slug :<input type="text" name="slug" id="slug" class="form-control" value="{{ old('name') }}"><br><br>
                Category Description: <textarea name="description" id="" cols="30" rows="10" class="form-control">{{ old('description') }}</textarea><br>
                Parent Category: 
                <x-forms.select name="parent_id" class="form-control">
                <option value='0'>Select</option>
                @foreach ($categories as $category)
                    <option value= "{{ $category->id }}"  {{ $category->id == old('parent_id') ? "selected": '' }}>{{$category->name}}</option>
                @endforeach   
                
                @error('category_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror   

                <input type="file" name="image_file" id="">
            </x-forms.select> <br>
                 <input type="submit" name="Submit" value="save" class="form-control">
            </form>
          </div>
        </div>
    </div>
</x-admin.layout>
<script>
    JQuert(document).ready(function($){
        $('#name').on('change'function(){
          var name = $('#name'.val());
          var slug = name.toLowerCase();  //slug lai lowercase ma lageko //
          var slug = name.replace(/\s+/g, '-'); //regular expression use garera slug ko space nikalera dash ma convert gareko//
          $('#slug').val(slug); //yesle category name ma rakheko name lai slug ko part ma lower case ma lekhdinxa//

        })
    })
    </script>

resources/views/admin/categories/edit.blade.php
<x-admin.layout>
    <div class="az-content az-content-dashboard">
        <div class="container">
          <div class="az-content-body">
            <h2>Edit Category</h2>
            <form action="{{ route('admin.categories.update', $category->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                {{-- <x-forms.input type="text" name='full_name'/>    esma j j atrributr rakhyo,tyo input.blade ma change garna milxa  --}}
                Category Name : <input type="text" name="name" id="name" class="form-control" value="{{ $category->name }}" 
                @error('name')
                    style="border-color: red;"
                @enderror
                >
                Category Slug :<input type="text" name="slug" id="slug" class="form-control" value="{{  $category->slug }}"><br><br>
                Category Description: <textarea name="description" id="" cols="30" rows="10" class="form-control">{{  $category->desc }}</textarea><br>
                Parent Category: 
                <x-forms.select name="parent_id" class="form-control">
                <option value='0'>Select</option>
                @foreach ($categories as $cat)
                    <option value= "{{ $cat->id }}"  {{ $category->parent_id == $cat->id ? "selected": '' }}>{{$cat->name}}</option>
                @endforeach   
                
                @error('category_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror   

                <input type="file" name="image_file" id="">
            </x-forms.select> <br>
                 <input type="submit" name="Submit" value="save" class="form-control">
            </form>
          </div>
        </div>
    </div>
</x-admin.layout>
<script>
    JQuert(document).ready(function($){
        $('#name').on('change'function(){
          var name = $('#name'.val());
          var slug = name.toLowerCase();  //slug lai lowercase ma lageko //
          var slug = name.replace(/\s+/g, '-'); //regular expression use garera slug ko space nikalera dash ma convert gareko//
          $('#slug').val(slug); //yesle category name ma rakheko name lai slug ko part ma lower case ma lekhdinxa//

        })
    })
    </script>

resources/views/admin/categories/index.blade.php
<x-admin.layout>
    <div class="az-content az-content-dashboard">
        <div class="container">
          <div class="az-content-body">
             <a href="{{ route('admin.categories.create') }}">Create Category</a> {{-- yo garda path change garepani dherai problem creatae gardaina --}}
                <table width='900' align='center'>
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Description</td>
            <td>Slug</td>
            <td>Action</td>
        </tr>
        @foreach ($categories as $category)
        <tr>
            <td>{{ $category->id}}</td>
            <td>{{ $category->name}}</td>
            <td>{{substr($category->description,0,50)}}</td>
            <td>{{$category->slug}}</td>
            <td>
                <a href="{{ route('admin.categories.edit',$category->id) }}">Edit</a>
                <form method="POST" action="{{route('admin.categories.destroy',$category->id)}}">
                    @method('DELETE')
                    @csrf
                    <a href="#" onclick="event.preventDefault();
                    this.closest('form').submit();"> Delete</a>
                    </form>
            </td>
        </tr>
        @endforeach
    </table>
          </div>
        </div>
    </div>
    </x-admin.layout>
    
    